package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

const puzzle = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`

func TestSolve_2025_Day3(t *testing.T) {
	area, startP := parseInput(puzzle)
	assert.Equal(t, 21, solvePart1(area, startP))

	//area, startP = parseInput(puzzle)
	//assert.Equal(t, 40, solvePart2(area, startP))
}
